### PR TITLE
Add PCA/MDS session

### PR DESCRIPTION
**Pull request by TCLamnidis**
Just realised I never actually opened this PR.

### CODE REVIEW

**Comment by llacher** [comment]
Looks good, except there are two parts without content: "Compare Plots" and "Conclusions".

**Comment by martynamolak** [comment]
I will do that asap

**Comment by stschiff** [comment]
Is this ready to merge, @martynamolak ?

**Comment by martynamolak** [comment]
> Is this ready to merge, @martynamolak ?

No, unfortunately I did not manage to go through it yet.
I'll try to do it today finally :)

**Comment by martynamolak** [comment]
I added the updated qmd, but it went as a separate pull request called "patch 3". I suck at Github...
Anyways, I would be grateful if @TCLamnidis could look at the comparison of the plots and conclusion sections and see whether I covered everything and whether I didn't write something entirely wrong :)

**Pull request merged**
