### PR TITLE
Add the mobest chapter

### PR DESCRIPTION
**Pull request by nevrome**
Please don't merge yet.

I was in a bit of an odd situation, because I already had a tutorial ready. This version of the text is now simplified for the presentation tomorrow. For the written version it may actually be better to go back again to the longer version.

### CODE REVIEW

**Comment by scarlhoff** [comment]
Hi @nevrome! What's the status on the website version of your tutorial? Thanks!

**Comment by nevrome** [comment]
I removed a lot of the text for the presentation, which I would like to add back for the write-up. Will get back to this in the next couple of weeks.

**Comment by scarlhoff** [comment]
Okay sounds good. Thank you!

**Comment by nevrome** [comment]
Ready for review now.

**Review by stschiff — APPROVED** [review]
Super extensive. Many thanks, @nevrome. I will merge this in and rebuild the website!

**Pull request merged**
