### PR TITLE
Poseidon introduction

### PR DESCRIPTION
**Pull request by nevrome**
@AyGhal and I are working on the Poseidon intro here.

### CODE REVIEW

**Review by stschiff — APPROVED** [review]
Excellent. Thanks. Good to merge from my end

**Comment by nevrome** [comment]
Note that this does not include the rendered pages. We didn't commit any changes to the `docs` directory.

**Review by llacher — APPROVED** [review]

**Comment by llacher** [comment]
Looks good to me as well

**Comment by jfy133** [comment]
Oh crap, sorry, I thought this was on my PR - I shouldn't git and baby :facepalm:  :face_with_spiral_eyes: 

But as you had two approvals I hope it's OK :sweat_smile:

**Comment by stschiff** [comment]
Yeah, I was getting confused. But OK. I'll merge your other one then 😅

**Comment by jfy133** [comment]
Sorry sorry :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:

**Pull request merged**
